# Stremlit configs.
# See <https://docs.streamlit.io/library/advanced-features/configuration>.
[browser]
  gatherUsageStats = false

[runner]
  fastReruns = false

[server]
  runOnSave = true

[client]
  showErrorDetails = true

[theme]
  base = "light"
  # Colors
  primaryColor = "#2BB5E8"
